LoadingProduct/LoadingProductWeb/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fish.Admin.Controllers;
using LoadingProductShared.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace LoadingProductWeb.Areas.Admin
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class HomeAdminController : Controller
    {
        #region General

        private readonly AppDBContext _dbContext;
        private readonly ILogger<HomeAdminController> _logger;

        public HomeAdminController(AppDBContext dbContext,
            ILogger<HomeAdminController> logger)
        {
            _dbContext = dbContext;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(MemberController.Index), "Member");
        }

        #endregion
    }
}

LoadingProduct/LoadingProductWeb/Areas/Admin/Controllers/MediaController.cs
using LoadingProductShared.Data;
using LoadingProductShared.Helpers;
using LoadingProductWeb.Admin.Models;
using LoadingProductWeb.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace LoadingProductWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MediaController : Controller
    {
        private readonly string mediaUrl;
        private readonly string mediaPath;

        private readonly ILogger _logger;
        private readonly AppDBContext _dbContext;

        public MediaController(
            ILogger<MediaController> logger,
            AppDBContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;

            mediaUrl = AppSettings.Strings["MediaUrl"] ?? "/media1";
            mediaPath = AppSettings.Strings["MediaPath"] ?? "./wwwroot/media";
        }

        public IActionResult FileBrowser(PagedList<MediaFile> model)
        {
            model.PageSize = 10;

            var filterQuery = _dbContext.MediaFiles.Where(x => model.Search == null || x.FileName.Contains(model.Search) || x.MediaAlbum.FullName.Contains(model.Search));
            var selectQuery = filterQuery.OrderByDescending(x => x.Id).Skip((model.CurPage - 1) * model.PageSize).Take(model.PageSize);

            model.TotalRows = filterQuery.Count();
            model.Content = selectQuery.ToList();

            foreach (var item in model.Content)
                item.FileLink = Path.Combine(mediaUrl, item.FullPath);

            return View(model);
        }

        public IActionResult FileManager(PagedList<MediaFile> model)
        {
            model.PageSize = 20;

            var filterQuery = _dbContext.MediaFiles.Where(x => (model.Search == null || x.FileName.Contains(model.Search) || x.MediaAlbum.FullName.Contains(model.Search))&& x.MediaAlbum.ShortName.Equals("Default"));
            var selectQuery = filterQuery.OrderByDescending(x => x.Id).Skip((model.CurPage - 1) * model.PageSize).Take(model.PageSize);

            model.TotalRows = filterQuery.Count();
            model.Content = selectQuery.ToList();

            foreach (var item in model.Content)
                item.FileLink = Path.Combine(mediaUrl, item.FullPath);

            return View(model);
        }
        public IActionResult Banner(PagedList<MediaFile> model)
        {
            model.PageSize = 20;

            //var filterQuery = _dbContext.MediaFiles.Include(y => y.MediaAlbum).Where(x => model.Search == null || x.FileName.Contains(model.Search) || x.MediaAlbum.FullName.Contains(model.Search) && x.MediaAlbum.ShortName.Equals("Banner"));

            var filterQuery = _dbContext.MediaFiles.Include(x => x.MediaAlbum).Where(x => (model.Search == null || x.FileName.Contains(model.Search) || x.MediaAlbum.FullName.Contains(model.Search)) && x.MediaAlbum.ShortName.Equals("Banner"));
            var selectQuery = filterQuery.OrderByDescending(x => x.Id).Skip((model.CurPage - 1) * model.PageSize).Take(model.PageSize);

            model.TotalRows = filterQuery.Count();
            model.Content = selectQuery.ToList();

            foreach (var item in model.Content)
                item.FileLink = Path.Combine(mediaUrl, item.FullPath);

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> FileUpload(int? id, IEnumerable<IFormFile> files)
        {
            MediaAlbum album = GetDefaultAlbum(id);
            if (album == null)
                return BadRequest("Could not create Default Album!");

            return await DoUploadFile(album, files, _dbContext);
        }

        [HttpPost]
        public async Task<IActionResult> FileUploadBanner(int? id, IEnumerable<IFormFile> files)
        {
            var albumBanner = _dbContext.MediaAlbums.Include(x => x.MediaFiles).Where(x => x.ShortName.Equals("Banner")).Select(x=>x.Id).FirstOrDefault();

            MediaAlbum album = GetDefaultAlbumBanner(albumBanner);
            if (album == null)
                return BadRequest("Could not create Default Album!");

            return await DoUploadFile(album, files, _dbContext);
        }
        private async Task<IActionResult> DoUploadFile(MediaAlbum album, IEnumerable<IFormFile> files, AppDBContext dbContext)
        {
            try
            {
                string albumDir = Path.Combine(mediaPath, album.ShortName);
                if (!Directory.Exists(albumDir))
                    Directory.CreateDirectory(albumDir);

                List<MediaFile> newFiles = new List<MediaFile>();
                foreach (var file in files)
                {
                    string fileName = file.FileName.ToLower();
                    string fileExt = Path.GetExtension(fileName);

                    while (true)
                    {
                        fileName = Common.Random_Mix(6).ToLower() + fileExt;
                        string filePath = Path.Combine(albumDir, fileName);
                        if (!System.IO.File.Exists(filePath))
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                                await file.CopyToAsync(stream);

                            break;
                        }
                    }

                    MediaFile newFile = new MediaFile()
                    {
                        AlbumId = album.Id,
                        FileName = file.FileName.ToLower(),
                        FullPath = Path.Combine(album.ShortName, fileName),
                        FileSize = file.Length,
                        CreateTime = DateTime.Now,
                    };

                    newFiles.Add(newFile);
                    dbContext.MediaFiles.Add(newFile);
                }

                dbContext.SaveChanges();
                return new JsonResult(new FileUploadResult
                {
                    initialPreview = newFiles.Select(x => Path.Combine(mediaUrl, x.FullPath)).ToArray(),
                    initialPreviewConfig = newFiles.Select(x => new { key = x.Id, caption = x.FileName, size = x.FileSize, showDrag = false }).ToArray(),
                });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    

        //[HttpPost]
        //public async Task<IActionResult> FileUploadProduct(int? id, IEnumerable<IFormFile> files)
        //{
        //    ShopItem model = _dbContext.ShopItems.Find(id);
        //    if (model == null)
        //        return BadRequest();

        //    if (model.MediaAlbum == null)
        //    {
        //        try
        //        {
        //            model.MediaAlbum = new MediaAlbum()
        //            {
        //                UserId = 1,
        //                ShortName = string.Format("Item{0:D4}", model.Id),
        //                FullName = "Album " + model.Name,
        //                CreateTime = DateTime.Now,
        //            };

        //            _dbContext.SaveChanges();
        //        }
        //        catch (Exception ex)
        //        {
        //            return BadRequest(ex.Message);
        //        }
        //    }

        //    return await DoUploadFile(model.MediaAlbum, files, _dbContext);
        //}

        [HttpPost]
        public IActionResult FileRemove(int? key)
        {
            MediaFile model = _dbContext.MediaFiles.Find(key);
            if (model == null)
                return BadRequest("File not found!");

            try
            {
                _dbContext.MediaFiles.Remove(model);
                _dbContext.SaveChanges();

                string fileName = Path.Combine(mediaPath, model.FullPath);
                if (System.IO.File.Exists(fileName))
                    System.IO.File.Delete(fileName);

                return Json(new ModalFormResult() { Code = 1, Message = "File deleted!" });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);

            }
        }
        private MediaAlbum GetDefaultAlbumBanner(int? id)
        {
            try
            {
                MediaAlbum album = _dbContext.MediaAlbums.FirstOrDefault(x => x.Id == id || x.ShortName == "Banner");
                if (album == null)
                {
                    album = new MediaAlbum()
                    {
                        UserId = 1,
                        ShortName = "Banner",
                        FullName = "Banner Album",
                        Description = "Album Banner",
                        CreateTime = DateTime.Now,
                    };

                    _dbContext.MediaAlbums.Add(album);
                    _dbContext.SaveChanges();
                }

                return album;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return null;
            }
        }
        private MediaAlbum GetDefaultAlbum(int? id)
        {
            try
            {
                MediaAlbum album = _dbContext.MediaAlbums.FirstOrDefault(x => x.Id == id || x.ShortName == "Default");
                if (album == null)
                {
                    album = new MediaAlbum()
                    {
                        UserId = 1,
                        ShortName = "Default",
                        FullName = "Default Album",
                        Description = "Album mặc định",
                        CreateTime = DateTime.Now,
                    };

                    _dbContext.MediaAlbums.Add(album);
                    _dbContext.SaveChanges();
                }

LoadingProduct/LoadingProductWeb/Areas/Admin/Controllers/ServiceLoadingProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LoadingProductShared.Data;
using LoadingProductShared.Helpers;
using LoadingProductWeb.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace LoadingProductWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ServiceLoadingProductController : Controller
    {
        private readonly ILogger _logger;
        private readonly AppDBContext _dbContext;

        public ServiceLoadingProductController(
            ILogger<ServiceLoadingProductController> logger,
            AppDBContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public IActionResult Index(PagedList<Service> model)
        {
            var filterQuery = _dbContext.Services.Where(x => model.Search == null || x.Title.Contains(model.Search));
            var selectQuery = filterQuery.OrderByDescending(x => x.Id).Skip((model.CurPage - 1) * model.PageSize).Take(model.PageSize);

            model.TotalRows = filterQuery.Count();
            model.Content = selectQuery.ToList();

            return View(model);
        }
        public ActionResult Details(int id)
        {
            var model = _dbContext.Services.Find(id);
            if (model == null)
                return BadRequest();

            return View(model);
        }

        public ActionResult Create()
        {
            return View(new Service());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(Service model)
        {
            if (!ModelState.IsValid)
                return View(model);
            try
            {
                model.CreateUser = User.Identity.Name;
                model.UpdateUser = User.Identity.Name;
                model.CreateTime = DateTime.Now;
                model.PublishTime = DateTime.Now;
                _dbContext.Services.Add(model);

                _dbContext.SaveChanges();
                model = new Service();
                return Redirect(Url.Action("Index"));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
        public IActionResult Update(int id)
        {
            var model = _dbContext.Services.Find(id);
            if (model == null)
                return BadRequest();

           return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Update(Service model)
        {
            if (ModelState.IsValid)
            {
                model.LastUpdate = DateTime.Now;
                model.UpdateUser = User.Identity.Name;
                _dbContext.Entry(model).State = EntityState.Modified;
                _dbContext.SaveChanges();
                
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: BlogPost/Delete/5
        public IActionResult Delete(int? id)
        {
            var model = _dbContext.Services.Find(id);
            if (model == null)
                return NotFound();

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Delete(Service model)
        {
            try
            {
                _dbContext.Entry(model).State = EntityState.Deleted;
                _dbContext.SaveChanges();
                return Json(new ModalFormResult() { Code = 1 });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(model);
        }

    }
}

LoadingProduct/LoadingProductWeb/Areas/Admin/Views/ServiceLoadingProduct/Create.cshtml
@using Newtonsoft.Json
@using LoadingProductShared.Helpers
@using Microsoft.AspNetCore.Html
@model Service
@{
    ViewBag.Icon = "fas fa-newspaper-o";
    ViewBag.Title = "Danh mục bài viết";
}

<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a asp-action="Index" asp-controller="HomeAdmin">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li>
                    <a asp-action="Index">
                        <i class="fa fas fa-newspaper-o"></i> Dịch vụ
                    </a>
                </li>
                <li>
                    <span>Thêm bài viết</span>
                </li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
            <a asp-action="Index" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Quay lại</a>
        </div>
    </div>
    <form asp-action="Create" method="post" autocomplete="off">
        <div class="modal-body">
            <partial name="_PartialForm" />
        </div>
        <br />
        <div class="modal-footer">
            <span id="progress" class="text-center" style="display: none;"><img src="~/img/wait.gif" alt="waiting..." />Saving...</span>
            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Lưu lại</button>
            <a asp-action="Index" class="btn btn-warning"><i class="fa fa-undo"></i> Hủy bỏ</a>
        </div>
    </form>
</section>

@section Scripts {
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/select2.min_VN.js"></script>
    <script src="~/js/summernote.min.js"></script>
    <script src="~/js/summernote-vi-VN.js"></script>
}

LoadingProduct/LoadingProductWeb/Areas/Admin/Views/ServiceLoadingProduct/Delete.cshtml
@model Service
@{
    Layout = null;
    ViewBag.Title = "Xóa dịch vụ";
}
<form class="modalForm" asp-action="Delete" method="post" autocomplete="off">
    <section class="card">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 class="modal-title"><i class="fa fa-windows"></i> @ViewBag.Title</h3>
        </div>
        <div class="modal-body">
            <div class="form-horizontal">
                @Html.ValidationSummary("", new { @class = "text-danger" })
                @Html.HiddenFor(m => m.Id)
                <div class="form-group">
                    @Html.LabelFor(m => m.Title, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.DisplayFor(m => m.Title)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Preview, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.DisplayFor(m => m.Preview)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CreateUser, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.DisplayFor(m => m.CreateUser)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CreateTime, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.DisplayFor(m => m.CreateTime)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.UpdateUser, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.DisplayFor(m => m.UpdateUser)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.LastUpdate, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.DisplayFor(m => m.LastUpdate)
                    </div>
                </div>
            </div>
            <h3 class="text-danger text-center">Bạn thực sự muốn xóa???</h3>
        </div>
        <div class="modal-footer text-right">
            <span id="progress" class="text-center" style="display: none;"><img src="~/img/wait.gif" alt="waiting..." />Saving...</span>
            <button class="btn btn-danger" type="submit"><i class="fa fa-times"></i> Xóa</button>
            <button class="btn btn-warning" data-dismiss="modal"><i class="fa fa-undo"></i> Hủy bỏ</button>
        </div>
    </section>
</form>

LoadingProduct/LoadingProductWeb/Areas/Admin/Views/ServiceLoadingProduct/Index.cshtml
@addTagHelper *,LoadingProductShared
@model PagedList<Service>
@{
    ViewBag.Icon = "fas fa-newspaper-o";
    ViewBag.Title = "Danh mục dịch vụ bốc xếp";
}

<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a asp-action="Index" asp-controller="HomeAdmin">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li>
                    <a asp-action="Index">
                        <i class="fa fa-newspaper-o"></i> Dịch vụ
                    </a>
                </li>
                <li>
                    <span>Danh sách</span>
                </li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
            <a class="btn btn-primary" href="@Url.Action("Create")"><i class="fa fa-plus"></i> Tạo mới</a>
            <a class="btn btn-warning" href="@Url.Action("Search")"><i class="fa fa-search"></i> Tìm nâng cao...</a>
        </div>
        <div class="col-sm-8 text-right">
            <form method="get" class="form-horizontal">
                <table style="margin-left: auto;">
                    <tr>
                        <td>
                            <select asp-for="PageSize" asp-items="Model.PageSelectList" class="form-control" style="width:120px;" onchange="this.form.submit();"></select>
                        </td>
                        <td>
                            <select asp-for="Filter" asp-items="@Html.GetEnumSelectList(typeof(EntityStatus))" class="form-control" style="width:160px;" onchange="this.form.submit();">
                                <option value="">== Trạng thái ==</option>
                            </select>
                        </td>
                        <td><input asp-for="Search" class="form-control" @style="width:240px;" @placeholder="Search" /></td>
                        <td><button class="btn btn-default" type="submit"><i class="fa fa-search"></i> Search</button></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="table-responsive">
        <pagination model="@Model" query-string="@Context.Request.QueryString" css-style="pagination pagination-sm"></pagination>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Hình đại diện</th>
                    <th>Tiêu đề</th>
                    <th>Giới thiệu</th>
                    <th>Người tạo</th>
                    <th>Ngày tạo</th>
                    <th>Người cập nhật</th>
                    <th>Ngày đăng</th>
                    <th>Thao tác</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Content)
                {
                <tr>
                    @if (string.IsNullOrEmpty(item.Image))
                    {
                        <td></td>
                    }
                    else
                    {
                        <td><img src='@item.Image' alt='Hình bài viết' style='max-height:80px;'></td>
                    }
                    <td>@Html.DisplayFor(m => item.Title)</td>
                    <td>@Html.DisplayFor(m => item.Preview)</td>
                    <td>@Html.DisplayFor(m => item.CreateUser)</td>
                    <td>@Html.DisplayFor(m => item.CreateTime)</td>
                    <td>@Html.DisplayFor(m => item.UpdateUser)</td>
                    <td>@Html.DisplayFor(m => item.PublishTime)</td>
                    <td>
                        @*@Html.DetailsLink("Details", new { id = item.Id })*@
                        @Html.UpdateLink("Update", new { id = item.Id })
                        @Html.DeleteLink("Delete", new { id = item.Id }, true)
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</section>

LoadingProduct/LoadingProductWeb/Areas/Admin/Views/ServiceLoadingProduct/Update.cshtml
@model Service
@{
    ViewBag.Icon = "fas fa-newspaper-o";
    ViewBag.Title = "Cập nhật dịch vụ";
}

<section role="main" class="content-body">
    <header class="page-header">
        <h2><i class="fa @ViewBag.Icon"></i> @ViewBag.Title</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a asp-action="Index" asp-controller="HomeAdmin">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li>
                    <a asp-action="Index">
                        <i class="fa fa-newspaper-o"></i> Dịch vụ
                    </a>
                </li>
                <li>
                    <span>Thêm dịch vụ</span>
                </li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-sm-4">
            <a asp-action="Index" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Quay lại</a>

        </div>
    </div>
    <form asp-action="Update" method="post" autocomplete="off">
        <div class="modal-body">
            <partial name="_PartialForm" />
        </div>
        <br />
        <div class="modal-footer">
            <span id="progress" class="text-center" style="display: none;"><img src="~/img/wait.gif" alt="waiting..." />Saving...</span>
            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Lưu lại</button>
            <a asp-action="Index" class="btn btn-warning"><i class="fa fa-undo"></i> Hủy bỏ</a>
        </div>
    </form>
</section>

@section Scripts {
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/select2.min_VN.js"></script>
}

LoadingProduct/LoadingProductWeb/Areas/Admin/Views/ServiceLoadingProduct/_PartialForm.cshtml
@using LoadingProductWeb.Areas.Admin.Models
@model Service
@{
    Layout = null;
}

<div class="form-horizontal">
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.CreateUser)
    @Html.HiddenFor(m => m.CreateTime)

    <div class="row">
        <div class="col-md-7">
            <div class="form-group">
                <label asp-for="Title" class="col-sm-3 control-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Title" class="form-control" , @required="" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TitleEn" class="col-sm-3 control-label"></label>
                <div class="col-sm-9">
                    <input asp-for="TitleEn" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Preview" class="col-sm-3 control-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Preview" class="form-control" , @required="" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="PreviewEn" class="col-sm-3 control-label"></label>
                <div class="col-sm-9">
                    <input asp-for="PreviewEn" class="form-control" />
                </div>
            </div>
        </div>
        <br />
        <div class="col-md-5">
            @if (@Model.Image == null)
            {
                <label asp-for="Image" class="col-md-4 control-label" style="width: 100%; font-size: 25px; text-align:center;"></label>
            }
            <div class="thumb-info mb-md">
                @Html.HiddenFor(m => m.Image)
                <br />
                <img src="@Model.Image" id="avatar" class="rounded img-responsive" alt="">
                <div class="thumb-info-title">
                    <a class="btn btn-primary" href="@Url.Action("FileBrowser", "Media", new { @input = "Image", @image = "avatar" })" data-modal="" title="Cập nhật hình đại diện"><i class="fa fa-edit"></i></a>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <h1>Nội dung</h1>
    <div class="form-group">
        <div class="col-md-12">
            @Html.SummerNoteFor(m => m.Content)
        </div>
    </div>
</div>